set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR "x64")

set(CMAKE_C_COMPILER   clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)

set(CMAKE_C_COMPILER_FRONTEND_VARIANT  MSVC)
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT MSVC)

set(CMAKE_LINKER lld-link)
